// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nkldjecnefduwmseyyih.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5rbGRqZWNuZWZkdXdtc2V5eWloIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyMjQwNjMsImV4cCI6MjA2OTgwMDA2M30.RVLRvO3hlAKxnzi_iz5qyklbzOwz-U-GprN__bA_3dQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});